question_repo/apps/accounts/forms.py
from django import forms
from django.forms import widgets
from django.core.exceptions import ValidationError
from django.contrib.auth.hashers import check_password as auth_check_password
from .models import User


# 用户注册
class RegisterForm(forms.ModelForm):
    password2 = forms.CharField(label="密 码2",
                                widget=widgets.PasswordInput(attrs={"class": "form-control", "placeholder": "请再输入密码"}))
    mobile_captcha = forms.CharField(label="验证码", widget=widgets.TextInput(
                                attrs={"style": "width: 160px;padding: 10px", "placeholder": "验证码", "error_messages": {"invalid": "验证码错误"}}))

    class Meta:
        model = User
        fields = ['username', 'mobile', 'password']
        widgets = {
            'username': widgets.TextInput(attrs={"class": "form-control", "placeholder": "请输入用户名"}),
            'mobile': widgets.TextInput(attrs={"class": "form-control", "placeholder": "请输入手机号"}),
            'password': widgets.PasswordInput(attrs={"class": "form-control", "placeholder": "请输入密码"}),
        }

    # username是否重复django会自动检查，因为它是unique的，所以不需要自己写clean_username

    def clean_mobile(self):
        ret = User.objects.filter(mobile=self.cleaned_data.get("mobile"))
        if not ret:
            return self.cleaned_data.get("mobile")
        else:
            raise ValidationError("手机号已绑定")

    def clean_password(self):
        data = self.cleaned_data.get("password")
        if not data.isdigit():
            return self.cleaned_data.get("password")
        else:
            raise ValidationError("密码不能全是数字")

    def clean(self):
        if self.cleaned_data.get("password") == self.cleaned_data.get("password2"):
            return self.cleaned_data
        else:
            raise ValidationError("两次密码不一致")

class LoginForm(forms.Form):
    username = forms.CharField(label="用户名", max_length="24",
                               widget=widgets.TextInput(attrs={"class": "form-control", "placeholder": "用户名"}))
    captcha = forms.CharField(label="验证码", widget=widgets.TextInput(
        attrs={"style": "width: 160px;padding: 10px", "placeholder": "验证码", "onblur": "check_captcha()",
               "error_messages": {"invalid": "验证码错误"}}))
    password = forms.CharField(label="密 码",
                               widget=widgets.PasswordInput(attrs={"class": "form-control", "placeholder": "请输入密码"}))

    def check_password(self):
        print('check password')
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        try:
            user = User.objects.get(username=username)
            return user, auth_check_password(password, user.password)
        except:
            return None, False

    def clean_username(self):
        print('hahaha')
        print(self.cleaned_data.get("username"))
        ret = User.objects.filter(username=self.cleaned_data.get("username"))
        if ret:
            return self.cleaned_data.get("username")
        else:
            raise ValidationError("用户名或密码不正确")

question_repo/templates/category.html
<section class="panel">
                              <div class="panel-body progress-panel">
                                  <div class="task-progress">
                                      <h1>类别排行榜</h1>
                                      <p>完成度排行</p>
                                  </div>
                              </div>
                              <table class="table table-hover personal-task">
                                  <tbody>
                                      <tr>
                                          <td>1</td>
                                          <td>
                                              <a href="#">网络题</a>
                                          </td>
                                          <td>
                                              <span>
                                                  <div class="progress progress-striped active progress-xs">
                                                      <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                                                          <span class="sr-only">45% Complete</span>
                                                      </div>
                                                  </div>
                                              </span>
                                          </td>
                                      </tr>
                                      <tr>
                                          <td>2</td>
                                          <td>
                                              <a href="#">网络题</a>
                                          </td>
                                          <td>
                                              <span>
                                                 <div class="progress progress-striped active progress-xs">
                                                      <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                                                          <span class="sr-only">45% Complete</span>
                                                      </div>
                                                  </div>
                                              </span>
                                          </td>
                                      </tr>
                                      <tr>
                                          <td>3</td>
                                          <td>
                                              <a href="#">网络题</a>
                                          </td>
                                          <td>
                                              <span>
                                                  <div class="progress progress-striped active progress-xs">
                                                      <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                                                          <span class="sr-only">45% Complete</span>
                                                      </div>
                                                  </div>
                                              </span>
                                          </td>
                                      </tr>
                                      <tr>
                                          <td>4</td>
                                           <td>
                                              <a href="#">网络题</a>
                                          </td>
                                          <td>
                                              <span>
                                                  <div class="progress progress-striped active progress-xs">
                                                      <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                                                          <span class="sr-only">45% Complete</span>
                                                      </div>
                                                  </div>
                                              </span>
                                          </td>
                                      </tr>
                                      <tr>
                                          <td>5</td>
                                           <td>
                                              <a href="#">网络题</a>
                                          </td>
                                          <td>
                                              <span>
                                                  <div class="progress progress-striped active progress-xs">
                                                      <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 45%">
                                                          <span class="sr-only">45% Complete</span>
                                                      </div>
                                                  </div>
                                              </span>
                                          </td>
                                      </tr>
                                  </tbody>
                              </table>
                            </section>

question_repo/templates/hot_topic.html
<section class="panel">
                          <div class="panel-body progress-panel">
                              <div class="task-progress">
                                  <h1>热门算法题目</h1>
                                  <p>答题人数最多的题目</p>
                              </div>
                          </div>
                          <table class="table table-hover personal-task">
                              <tbody>
                                  <tr>
                                      <td>1</td>
                                      <td>
                                          <a href="http://127.0.0.1:8000/question/7679/" title="sql优化">7679. sql优化</a>
                                      </td>
                                      <td>
                                          <span class="label label-info">入门</span>
                                      </td>
                                  </tr>
                                  <tr>
                                      <td>2</td>
                                      <td>
                                          <a href="http://127.0.0.1:8000/question/7576/" title="三次握手">7576. 三次握手</a>
                                      </td>
                                      <td>
                                          <span class="label label-info">入门</span>
                                      </td>
                                  </tr>
                                  <tr>
                                      <td>3</td>
                                      <td>
                                          <a href="http://127.0.0.1:8000/question/7567/" title="单向链表如何使用快速排序算法进行排序；">7567. 单向链表如何使...</a>
                                      </td>
                                      <td>
                                              <span class="label label-info">入门</span>
                                      </td>
                                  </tr>
                                  <tr>
                                      <td>4</td>
                                      <td>
                                          <a href="http://127.0.0.1:8000/question/7584/" title="HTTP和HTTPS">7584. HTTP和HTTPS</a>
                                      </td>
                                      <td>
                                              <span class="label label-info">入门</span>
                                      </td>
                                  </tr>
                                  <tr>
                                      <td>5</td>
                                      <td>
                                          <a href="http://127.0.0.1:8000/question/7580/" title="Post和Get">7580. Post和Get</a>
                                      </td>
                                      <td>
                                              <span class="label label-info">入门</span>
                                      </td>
                                  </tr>
                              </tbody>
                          </table>
                      </section>

question_repo/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}首页{% endblock %}

{% block content %}
    {% include 'crontribute_modal.html' %}
<aside class="profile-info col-lg-9">
    <!--features carousel start-->
    <section class="panel">
          <div class="flat-carousal">
              <div id="owl-demo" class="owl-carousel owl-theme" style="opacity: 1; display: block;">
                  <div class="owl-wrapper-outer">
                      <div class="owl-wrapper" style="width: 4926px; left: 0px; display: block;">
                          <div class="owl-item active" style="width: 821px;">
                              <div class="item">
                                  <h1>通知广告1</h1>
                                  <div class="text-center">
                                      <a href="javascript:;" class="view-all">View All</a>
                                  </div>
                              </div>
                          </div>
                          <div class="owl-item" style="width: 821px;">
                              <div class="item">
                                  <h1>通知广告2</h1>
                                  <div class="text-center">
                                      <a href="javascript:;" class="view-all">View All</a>
                                  </div>
                              </div>
                          </div>
                          <div class="owl-item" style="width: 821px;">
                              <div class="item">
                                  <h1>通知广告3</h1>
                                  <div class="text-center">
                                      <a href="javascript:;" class="view-all">View All</a>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>

                  <div class="owl-controls clickable">
                      <div class="owl-pagination">
                          <div class="owl-page active"><span class=""></span></div>
                          <div class="owl-page"><span class=""></span></div>
                          <div class="owl-page"><span class=""></span></div>
                      </div>
                      <div class="owl-buttons">
                          <div class="owl-prev">prev</div>
                          <div class="owl-next">next</div>
                      </div>
                  </div>
              </div>
          </div>
    </section>
    <!--features carousel end-->

    <section class="panel">
          <header class="panel-heading">
              最新动态
          </header>
          <div class="panel-body">
              <div class="timeline-messages">
                  <!-- Comment -->
                  {% for item in userlog %}
                  <div class="msg-time-chat">
                      <a href="#" class="message-img"><img class="avatar" src="{{ item.user.avator_sor.url }}" alt=""></a>
                      <div class="message-body {% if forloop.counter|divisibleby:2  %} msg-out {% else %}msg-in{% endif %}">
                          <span class="arrow"></span>
                          <div class="text">

                              <p class="attribution"><a href="#">{{ item.user.username }}</a>{{ item.create_time  }}</p>

                              {% if item.question %}
                              <p>{{ item.operate_cn }}了<a href="{% url 'repo:question_detail' item.question.id %}">{{ item.question.title }}</a></p>
                              {% else %}
                              <p>{{ item.operate_cn }}了<a href="{% url 'repo:question_detail' item.answer.question.id %}">{{ item.answer.question.title }}</a></p>
                              {% endif %}
                          </div>
                      </div>
                  </div>
                  <!-- /comment -->
                 {%  endfor%}
                  <!-- Comment -->
              </div>
          </div>
    </section>

    <!--最近刷题的同学 start-->
    <section class="panel">
        <header class="panel-heading">
          最近刷题的同学
        </header>
        <div class="panel-body">
            {% for user in recent_user %}
             <div class="task-thumb">
                 <img src="{{ user.avator_sor.url  }}" alt="">
                 <div class="clearfix"></div>
                 <a href="#">{{ user.username }}</a>
            </div>
            {% endfor %}
             <div class="task-thumb">
                 <img src="{% static 'img/1534407125.png' %}" alt="">
                 <div class="clearfix"></div>
                 <a href="#">aaa</a>
            </div>
        </div>
    </section>
    <!--custom chart end-->
</aside>
<aside class="profile-info col-lg-3">
  <!--follower start-->
  <section class="panel">
      <div class="follower">
          <div class="panel-body">
              <div class="follow-ava">
                  <img src="{{ request.user.avator_sor.url }}" alt="">
              </div>
              <h4>{{ request.user.username }}</h4>
              <h4>您已完成 {{ user_data.answer_num }} 道面试题，加油！</h4>
          </div>
      </div>
      <footer class="follower-foot">
          <ul>
              <li>
                  <h4>{{ user_data.answer_num }}/{{ user_data.question_all }}</h4>
                  <p>刷题量{%  widthratio user_data.answer_num user_data.question_all 100 %}</p>
              </li>
              <li>
                  <h4>第{{ user_data.rank.rank }}名</h4>
                  <p>当前排名：{{ user_data.rank.rank }}/{{ user_data.user_sum }}</p>
              </li>
          </ul>
      </footer>
  </section>
  <!--follower end-->
  <!--热门题目 start-->
  <section class="panel">
      <div class="panel-body progress-panel">
          <div class="task-progress">
              <h1>热门算法题目</h1>
              <p>答题人数最多的题目</p>
          </div>
      </div>
      <table class="table table-hover personal-task">
          <tbody>
{#              <tr>#}
{#                  <td>1</td>#}
{#                  <td>#}
{#                      <a href="http://127.0.0.1:8000/question/7679/" title="sql优化">7679. sql优化</a>#}
{#                  </td>#}
{#                  <td>#}
{#                      <span class="label label-info">入门</span>#}
{#                  </td>#}
{#              </tr>#}
{#              <tr>#}
{#                  <td>2</td>#}
{#                  <td>#}
{#                      <a href="http://127.0.0.1:8000/question/7576/" title="三次握手">7576. 三次握手</a>#}
{#                  </td>#}
{#                  <td>#}
{#                      <span class="label label-info">入门</span>#}
{#                  </td>#}
{#              </tr>#}
{#              <tr>#}
{#                  <td>3</td>#}
{#                  <td>#}
{#                      <a href="http://127.0.0.1:8000/question/7567/" title="单向链表如何使用快速排序算法进行排序；">7567. 单向链表如何使...</a>#}
{#                  </td>#}
{#                  <td>#}
{#                          <span class="label label-info">入门</span>#}
{#                  </td>#}
{#              </tr>#}
{#              <tr>#}
{#                  <td>4</td>#}
{#                  <td>#}
{#                      <a href="http://127.0.0.1:8000/question/7584/" title="HTTP和HTTPS">7584. HTTP和HTTPS</a>#}
{#                  </td>#}
{#                  <td>#}
{#                          <span class="label label-info">入门</span>#}
{#                  </td>#}
{#              </tr>#}
{#              <tr>#}
{#                  <td>5</td>#}
{#                  <td>#}
{#                      <a href="http://127.0.0.1:8000/question/7580/" title="Post和Get">7580. Post和Get</a>#}
{#                  </td>#}
{#                  <td>#}
{#                          <span class="label label-info">入门</span>#}
{#                  </td>#}
{#              </tr>#}
          {% for item in hot_question %}
          <tr>
              <td>{{ forloop.counter }}</td>
              <td>
                  <a href="{% url 'repo:question_detail' item.id %}" title="{{ item.title }}">{{ item.id }}. {{ item.title|truncatechars:10 }}</a>
              </td>
              <td>
                  {% if item.grade == 1 %}
                      <span class="label label-info">入门</span>
                  {% elif  item.grade == 2 %}
                      <span class="label label-info">简单</span>
                  {% elif  item.grade == 3 %}
                      <span class="label label-success">一般</span>
                  {% elif  item.grade == 4 %}
                      <span class="label label-danger">困难</span>
                  {% elif  item.grade == 5 %}
                      <span class="label label-danger">超难</span>
                  {% endif %}
              </td>
          </tr>
          {% endfor %}
          </tbody>
      </table>
  </section>
  <!--work progress end-->
  <!--近30天刷题用户排行榜 start-->
  <section class="panel">
      <div class="panel-body progress-panel">
          <div class="task-progress">
              <h1>近30天刷题用户排行榜</h1>
              <p></p>
          </div>
      </div>
      <table class="table table-hover personal-task">
          <tbody>
{#              <tr>#}
{#                  <td>1</td>#}
{#                  <td>#}
{#                      <a href="">admin</a>#}
{#                  </td>#}
{#                  <td>#}
{#                      <span>1/489</span>#}
{#                  </td>#}
{#              </tr>#}
          {% for item in hot_user %}
                      <tr>
                          <td>{{ forloop.counter }}</td>
                          <td>
                              <a href="">{{ item.user__username }}</a>
                          </td>
                          <td>
                              <span>{{ item.id__count }}/{{ user_data.question_all }}</span>
                          </td>
                      </tr>
                  {% endfor %}
          </tbody>
      </table>
  </section>
  <!--work progress end-->
</aside>
{% endblock %}

question_repo/templates/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="http://127.0.0.1:8000/accounts/login/img/favicon.html">
    <title>用户登录-三创题库系统</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static '/css/bootstrap-reset.css' %}" rel="stylesheet">
    <!--external css-->
    <link href="{% static '/assets/font-awesome/css/font-awesome.css' %}" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="{% static '/css/style.css' %}" rel="stylesheet">
    <link href="{% static '/css/style-responsive.css' %}" rel="stylesheet" />
    <script src="{% static '/js/jquery.js' %}"></script>
</head>
    <body class="login-body">
        <div class="container">
<form class="form-signin" action="{% url "accounts:login" %}" method="post">
        {% csrf_token %}
        <h2 class="form-signin-heading">登录</h2>
        <div class="login-wrap">
            {{ form.username}}
            {{ form.password}}
            {{ form.captcha}}
            <a href="javascript:void(0);"><img id="captcha_img" src="#" /></a>
            <label class="checkbox">
                <input type="checkbox" value="remember-me"> 记住密码
                <span class="pull-right"> <a href="{% url 'uc:password_forget' %}"> 忘记密码?</a></span>
            </label>
            <button class="btn btn-lg btn-login btn-block" type="submit">登录</button>
            <p class="msg"></p>
            {% if msg %}
            <div class="alert alert-block alert-danger fade in">
                  <button data-dismiss="alert" class="close close-sm" type="button">
                      <i class="icon-remove"></i>
                  </button>
                  <strong>提醒!</strong> {{ msg }}
            </div>
            {% endif %}
        </div>
      </form>
        </div>
    <script>
    get_captcha_img();
    $("#captcha_img").click(get_captcha_img);

    function get_captcha_img() {
        $.ajax({
            url: '{% url 'apis:get_captcha' %}',
            type: 'GET',
            dataType: 'text',
            success: function (data) {
                $('#captcha_img').attr('src', data);
            }
        });
    }
    </script>
    <script>
    // 这里在form中定义了，如果没定义可以用jquery添加事件
    // $("#id_captcha").blur(check_captcha);

    // 当失去焦点时检查验证码
    function check_captcha() {
        var captcha_code = $('#id_captcha').val();
        if (captcha_code.length == 0){
            return false
        }
        $.ajax({
            url: '{% url 'apis:check_captcha' %}',
            type: 'GET',
            dataType: 'json',
            data: {"captcha_code": captcha_code},
            success: function (data) {
                if(data.code == 400){
                     $('.msg').html("验证码错误");
                }else{
                    $('.msg').html("");
                }
            }
        });
    }
    </script>
    </body>
</html>

question_repo/templates/password_forget.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>忘记密码</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    请输入绑定的邮箱:<input type="email" placeholder="邮箱" name="email">
    <input type="submit" value="提交">
    {{ msg }}
</form>
</body>
</html>

question_repo/templates/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>忘记密码</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    密码1:<input type="password" placeholder="请输入密码" name="password1">
    密码2:<input type="password" placeholder="请再次输入密码" name="password2">
    <input type="submit" value="提交">
    {{ msg }}
</form>
</body>
</html>

question_repo/templates/question_detail_other_answer.html
{% load staticfiles %}
<div class="timeline-messages">
  {% for item in other_answer %}
  <!-- Comment -->
  <div class="msg-time-chat">
      <a href="#" class="message-img"><img class="avatar" src="{{ item.user.avator_sor.url }}" alt="图片不存在"></a>
      <div class="message-body msg-in">
          <span class="arrow"></span>
          <div class="text" style="line-height: 26px">
              <p class="attribution"><a href="#">{{ item.user }}</a> {{ item.last_modify }}</p>
              <p>{{ item.answer }}</p>

              <a class="glyphicon glyphicon-heart{% if not item.collect_status %}-empty{% endif %} answer-id-{{ item.id }}" aria-hidden="true" href="javascript:void(0);" onclick="collection({{ item.id }})">收藏(<span>{{ item.collect_nums }}</span>)</a>
{#              <a class="glyphicon glyphicon-heart{% if not item.collect_status %}-empty{% endif %} answer-collect" aria-hidden="true" href="javascript:void(0);" onclick="collection({{ item.id }})">收藏(<span>{{ item.collect_nums }}</span>)</a>#}
          </div>
      </div>
  </div>
  <!-- /comment -->
  {% endfor %}
</div>


<script>
    //todo => collection(answer_id)
    // ajax => /apis/answer/collection/answer_id/ => sucess: 修改图标/收藏量
    // django => url => view => return


    function collection(answer_id) {
        $.ajax({
            url: '/apis/answer/collection/'+ answer_id +'/',
            type: 'GET',
{#            dataType: 'json',#}
            success: function (data) {
                //alert(data);
                console.log(data);
                if(data.code == 200){
                    obj_a = $(".answer-id-"+answer_id);
                    obj_span = $(".answer-id-"+answer_id+" span");
                    if(data.msg.status){
                        obj_a.attr("class", "glyphicon glyphicon-heart "+"answer-id-"+answer_id)
                    }else{
                        obj_a.attr("class", "glyphicon glyphicon-heart-empty "+"answer-id-"+answer_id)
                    }
                    obj_span.html(data.msg.collections);
                }
            },
            error: function () {
                alert('error');
            }
        })
    }

</script>

question_repo/templates/ranging_list.html
<section class="panel">
                              <div class="panel-body progress-panel">
                                  <div class="task-progress">
                                      <h1>近30天刷题用户排行榜</h1>
                                      <p></p>
                                  </div>
                              </div>
                              <table class="table table-hover personal-task">
                                  <tbody>
                                      <tr>
                                          <td>1</td>
                                          <td>
                                              <a href="">admin</a>
                                          </td>
                                          <td>
                                              <span>1/489</span>
                                          </td>
                                      </tr>
                                  </tbody>
                              </table>
                            </section>

question_repo/templates/uc_answer.html
{% extends 'uc_base.html' %}
{% load staticfiles %}
{% block uc_content %}
  <div class="row">
      <div class="col-lg-12">
          <section class="panel">
              <header class="panel-heading">
                  Dynamic Table
              </header>
              <table class="table table-striped border-top" id="sample_1">
              <thead>
              <tr>
                  <th style="width:8px;"><input type="checkbox" class="group-checkable" data-set="#sample_1 .checkboxes" /></th>
                  <th class="hidden-phone">问题</th>
                  <th class="hidden-phone">我的答案</th>
                  <th class="hidden-phone">收藏量</th>
              </tr>
              </thead>
              <tbody>
              {% for answer in my_answers %}
              <tr class="odd gradeX">
                  <td><input type="checkbox" class="checkboxes" value="1" /></td>
                  <td><a href="{% url 'repo:question_detail' answer.question_id %}">{{ answer.question.title }}</a></td>
                  <td>{{ answer.answer }}</td>
                  <td>{{ answer.answers_collection_set.count }}</td>
              </tr>
              {% endfor %}
              </tbody>
              </table>
          </section>
      </div>
  </div>
  <!-- page end-->
{% endblock %}
{% block load_js %}
    <script type="text/javascript" src="{% static 'assets/data-tables/jquery.dataTables.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/data-tables/DT_bootstrap.js '%}"></script>
    <script src="{% static 'js/dynamic-table.js' %}"></script>
{% endblock %}